aura: Internal API
Internal API
Functions
void aura_object_migration_failed_cb (struct aura_node *node, void(*cb)(struct aura_node *node, struct aura_object *failed, void *arg), void *arg)
int aura_core_start_call (struct aura_node *node, struct aura_object *o, void(*calldonecb)(struct aura_node *dev, int status, struct aura_buffer *ret, void *arg), void *arg, struct aura_buffer *buf)
int aura_core_call (struct aura_node *node, struct aura_object *o, struct aura_buffer **retbuf, struct aura_buffer *argbuf)
Detailed Description
This group contains advanced API that can be used by language bindings
Function Documentation
int aura_core_call (struct aura_node * node, struct aura_object * o, struct aura_buffer ** retbuf, struct aura_buffer * argbuf)
Synchronously call an object. arguments should be placed in argbuf. The retbuf will be set to point to response buffer if the call succeeds.
Parameters
node
o
retbuf
argbuf
Returns
Definition at line 412 of file aura.c.
References aura_core_start_call(), and aura_handle_events().
Referenced by aura_call(), and aura_call_raw().
int aura_core_start_call (struct aura_node * node, struct aura_object * o, void(*)(struct aura_node *dev, int status, struct aura_buffer *ret, void *arg) calldonecb, void * arg, struct aura_buffer * buf)
Start a call for object obj for node . Normally you do not need this function - use aura_call() and aura_call_raw() synchronous calls and aura_start_call() and aura_start_call_raw() for async.
Parameters
node
o
calldonecb
arg
buf
Returns
Definition at line 361 of file aura.c.
References aura_queue_buffer(), and aura_buffer::object.
Referenced by aura_core_call(), aura_start_call(), and aura_start_call_raw().
void aura_object_migration_failed_cb (struct aura_node * node, void(*)(struct aura_node *node, struct aura_object *failed, void *arg) cb, void * arg)
When a node goes offline and online aura will try to migrate all the callbacks to a newly created export table Warning: This callback will not be called if you enable synchronous event processing
Parameters
node
cb The callback function to call
arg Argument that will be passed to the callback function
Definition at line 339 of file aura.c.