Document: aura
Title: Debian aura Manual
Author: <insert document author here>
Abstract: This manual describes what aura is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aura/aura.sgml.gz

Format: postscript
Files: /usr/share/doc/aura/aura.ps.gz

Format: text
Files: /usr/share/doc/aura/aura.text.gz

Format: HTML
Index: /usr/share/doc/aura/html/index.html
Files: /usr/share/doc/aura/html/*.html
